### ISSUE TITLE
Assignment2a

### ISSUE THREAD

**Issue by vkats-spbu** [sergey-cherepanov1/HomeAssignments#3]
Запускаю в точности по README.md:

<pre>victor@victor-VirtualBox:~/accesment/anisimov-vs/HomeAssignments/Assignment2/Assignment2b/sergey-cherepanov1/HomeAssignments/Assignment2a$ ./Assignment2a
terminate called after throwing an instance of &apos;std::filesystem::__cxx11::filesystem_error&apos;
  what():  filesystem error: cannot get file size: No such file or directory [sample]
Aborted (core dumped)</pre>

Укажите в README.md как должен называться и где располагаться файл, с которым работаете

**Comment by sergey-cherepanov1** [comment]
Указал.

**Comment by vkats-spbu** [comment]
приложенный входной файk дает на выходе программы пустой файл
[sample.txt](https://github.com/user-attachments/files/17291534/sample.txt)

**Comment by sergey-cherepanov1** [comment]
Исправил.

**Comment by vkats-spbu** [comment]
В условиях задачи файл бинарный - в нем не должно быть строк, и символ конца строки может играть любую роль. std::getline фактически пропускает символ конца строки и символ конца текстового файйла, поэтому в выходном файле получилось 2 байта вместо 4.

**Comment by sergey-cherepanov1** [comment]
Поправил. Вроде теперь всё как надо работает.
