### ISSUE TITLE
Assignment2b

### ISSUE THREAD

**Issue by vkats-spbu** [sergey-cherepanov1/HomeAssignments#4]
<pre>victor@victor-VirtualBox:~/accesment/anisimov-vs/HomeAssignments/Assignment2/Assignment2b/sergey-cherepanov1/HomeAssignments/Assignment2b$ ./Assignment2b
Введите строку в формате ОПЗ:
7 2 /
Ответ: 3
Введите строку в формате ОПЗ:
7.0 2 /
Ответ: 3
Введите строку в формате ОПЗ:
7.0 2.0 /
Ответ: 3
</pre>

7/2=3,5

Переделайте на работу с float или double

**Comment by vkats-spbu** [comment]
Также обратите внимание, что рабочий язык в коде и репозитории у нас - английский

**Comment by sergey-cherepanov1** [comment]
Сделал.

**Comment by vkats-spbu** [comment]
victor@victor-VirtualBox:~/accesment/sergey-cherepanov1/HomeAssignments/Assignment2b$ ./Assignment2b
Enter the string in RPN format:
1 1 7 2 +
Answer: 9
double free or corruption (out)
Aborted (core dumped)

Проверьте работу с некорректной входной строкой: сейчас в стеке остались две лишние единицы

**Comment by sergey-cherepanov1** [comment]
Поправил.
